swagger: "2.0"
info: 
  title: "Swagger Sample App"
  description: "Please click Terms of service"
  termsOfService: "https://example.com/terms"
  contact: 
    name: "API Support"
    url: "https://example.com/support"
    email: "support@example.com"
  version: "1.0.1"
